// <auto-generated />
using System;
using Hogwards.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hogwards.Migrations
{
    [DbContext(typeof(HogwartsdbContext))]
    [Migration("20260708001727_SyncModels")]
    partial class SyncModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hogwards.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateTrigerred")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("LogMessage")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id")
                        .HasName("PK__AuditLog__3214EC077B5BB6DE");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Hogwards.Models.HousePoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateRecorded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("WizardId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__HousePoi__3214EC07085F3163");

                    b.HasIndex("SubjectId");

                    b.HasIndex("WizardId");

                    b.ToTable("HousePoints");
                });

            modelBuilder.Entity("Hogwards.Models.MaraudersMapLog", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackId"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("MovementTime")
                        .HasColumnType("datetime");

                    b.Property<string>("WizardName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TrackId")
                        .HasName("PK__Marauder__7A74F8E0251A6D6E");

                    b.HasIndex(new[] { "MovementTime" }, "IX_MaraudersMapLogs_MovementTime");

                    b.ToTable("MaraudersMapLogs");
                });

            modelBuilder.Entity("Hogwards.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Teacher")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Subjects__3214EC070009E3CD");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Hogwards.Models.Wand", b =>
                {
                    b.Property<int>("WandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WandId"));

                    b.Property<string>("CoreMaterial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Length")
                        .HasColumnType("decimal(4, 1)");

                    b.Property<int>("WizardId")
                        .HasColumnType("int");

                    b.HasKey("WandId")
                        .HasName("PK__WANDS__BB49E3C8E14BFDCE");

                    b.HasIndex(new[] { "WizardId" }, "UQ_Wands_WizardId")
                        .IsUnique();

                    b.ToTable("WANDS", (string)null);
                });

            modelBuilder.Entity("Hogwards.Models.Wizard", b =>
                {
                    b.Property<int>("WizardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WizardId"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("BloodStatus")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Unknown", "DF_Wizard_BloodStatus");

                    b.Property<int?>("EntryYear")
                        .HasColumnType("int");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("WizardId")
                        .HasName("PK__Wizards__EB46AA85423A4160");

                    b.HasIndex(new[] { "Name" }, "IX_Wizards_Name");

                    b.ToTable("Wizards");
                });

            modelBuilder.Entity("Hogwards.Models.vw_ActiveWizard", b =>
                {
                    b.Property<string>("BloodStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WizardId")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_ActiveWizards", (string)null);
                });

            modelBuilder.Entity("Hogwards.Models.HousePoint", b =>
                {
                    b.HasOne("Hogwards.Models.Subject", "Subject")
                        .WithMany("HousePoints")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__HousePoin__Subje__0B91BA14");

                    b.HasOne("Hogwards.Models.Wizard", "Wizard")
                        .WithMany("HousePoints")
                        .HasForeignKey("WizardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__HousePoin__Wizar__0A9D95DB");

                    b.Navigation("Subject");

                    b.Navigation("Wizard");
                });

            modelBuilder.Entity("Hogwards.Models.Wand", b =>
                {
                    b.HasOne("Hogwards.Models.Wizard", "Wizard")
                        .WithOne("Wand")
                        .HasForeignKey("Hogwards.Models.Wand", "WizardId")
                        .IsRequired()
                        .HasConstraintName("FK_Wands_Wizards");

                    b.Navigation("Wizard");
                });

            modelBuilder.Entity("Hogwards.Models.Subject", b =>
                {
                    b.Navigation("HousePoints");
                });

            modelBuilder.Entity("Hogwards.Models.Wizard", b =>
                {
                    b.Navigation("HousePoints");

                    b.Navigation("Wand");
                });
#pragma warning restore 612, 618
        }
    }
}
